language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
install:
  - pip install "coverage<4" coveralls codecov
script:
  - nosetests --with-coverage --cover-package=rigidity
after_success:
  - coveralls
  - codecov
